# -*- coding: utf-8 -*-
"""setting_metadata.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OkBFkRNx03j3fH2IaVtkJeR-FGnKVYKi
"""

from langchain_core.documents import Document

'''
경로의 json 파일 읽어오기
json 리스트 형태여야 함.
'''
import json
with open('/content/Wanted_jobPost_List.json', 'r', encoding='utf-8') as file:
    content = file.read().strip()

data = json.loads(content)

'''
공고의 항목 지정, str내용에 들어갈 순서 지정
'''
jobPostingItem = [
        "회사 소개",
        "주요 업무",
        "자격 요건",
        "우대 사항",
        "복지",
        "채용절차",
        "장점",
        "제목",
        "회사명",
        "근무지",
        "지역",
        "직군",
        "직무",
        "요구 최소 경력",
        "요구 최대 경력",
        "신입 지원 가능 여부",
        "마감일"]

# metadata (추가 기입) : [source : 채용 공고, 공고id : 리스트 인덱스 번호]
# metadata (데이터 안 정보) : [근무지, 지역, 직군, 요구 최소 경력(int), 요구 최대 경력(int), 신입 지원 가능 여부(bool), 회사 이름]
# content 형식 : 평문

'''
input : jobPosting(dict) 공고, jobPostingItem(list) 공고의 항목
output : (str) 공고 내용 전체
'''
def makeFlatContent(jobPosting, jobPostingItem):
    content = ""
    for i in range(len(jobPostingItem)):
        next_content = jobPostingItem[i]+"은 '"+str(jobPosting[jobPostingItem[i]])+"'입니다.\n"
        content += next_content
    return content
'''
input : document(Document 객체 list), data : 읽어들인 파일, index : 리스트 인덱스 번호
output : None
'''
def setMetadata(document:list, data:list, index:int):
    document[index].metadata['source'] = "채용 공고"
    document[index].metadata['공고id'] = index
    document[index].metadata['근무지'] = str(data[index]['근무지'])
    document[index].metadata['지역'] = str(data[index]['지역'])
    document[index].metadata['직군'] = str(data[index]['직군'])
    # document[index].metadata['요구 최소 경력'] = int(data[index]['요구 최소 경력'])
    # document[index].metadata['요구 최대 경력'] = int(data[index]['요구 최대 경력'])
    document[index].metadata['신입 지원 가능 여부'] = bool(data[index]['신입 지원 가능 여부'])
    document[index].metadata['회사명'] = str(data[index]['회사명'])
'''
document_list 에 파일 전체를 문서로 저장함과, 메타데이터로 지정한 값을 저장함.
'''
document_list = []
for i in range(len(data)):
    content = makeFlatContent(data[i], jobPostingItem)
    document = Document(content)
    document_list.append(document)
    setMetadata(document_list,data,i)
# print(len(document_list))

### documennt_list를 기존 데이터 로드의 docs로 사용하면 됨. ###